ERROR - 2025-03-07 13:03:35 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\projects\tcc\Phpigni\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\projects\tcc\Phpigni\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\projects\tcc\Phpigni\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\projects\tcc\Phpigni\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\projects\tcc\Phpigni\app\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(933): App\Controllers\AuthController->register()
#10 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\projects\tcc\Phpigni\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\projects\tcc\Phpigni\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\projects\tcc\Phpigni\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\projects\tcc\Phpigni\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-03-07 13:03:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: api/register]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (:uid:, :email:, :crp:, :nome:, :telefone:, :data:, :sexo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
CRITICAL - 2025-03-07 13:03:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:03:35\', \'2025-03-07 13:03:35\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:03:35\', \'2025-03-07 13:03:35\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (:uid:, :email:, :crp:, :nome:, :telefone:, :data:, :sexo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
CRITICAL - 2025-03-07 13:03:35 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:03:35\', \'2025-03-07 13:03:35\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:03:35\', \'2025-03-07 13:03:35\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:03:35\', \'2025-03-07 13:03:35\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (:uid:, :email:, :crp:, :nome:, :telefone:, :data:, :sexo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
ERROR - 2025-03-07 13:08:39 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\projects\tcc\Phpigni\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\projects\tcc\Phpigni\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\projects\tcc\Phpigni\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\projects\tcc\Phpigni\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\projects\tcc\Phpigni\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\projects\tcc\Phpigni\app\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(933): App\Controllers\AuthController->register()
#10 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\xampp\htdocs\projects\tcc\Phpigni\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\projects\tcc\Phpigni\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\projects\tcc\Phpigni\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\projects\tcc\Phpigni\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\projects\tcc\Phpigni\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-03-07 13:08:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: api/register]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (:uid:, :email:, :crp:, :nome:, :telefone:, :data:, :sexo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
CRITICAL - 2025-03-07 13:08:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:08:39\', \'2025-03-07 13:08:39\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:08:39\', \'2025-03-07 13:08:39\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (:uid:, :email:, :crp:, :nome:, :telefone:, :data:, :sexo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
CRITICAL - 2025-03-07 13:08:39 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:08:39\', \'2025-03-07 13:08:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:08:39\', \'2025-03-07 13:08:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (\'12345\', \'usuario@example.com\', \'123456\', \'Fulano de Tal\', \'11999999\', \'01/01/1990\', \'Masculino\', \'2025-03-07 13:08:39\', \'2025-03-07 13:08:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`uid`, `email`, `crp`, `nome`, `telefone`, `data`, `sexo`, `created_at`, `updated_at`) VALUES (:uid:, :email:, :crp:, :nome:, :telefone:, :data:, :sexo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(23): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
CRITICAL - 2025-03-07 13:32:43 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:any)"
[Method: GET, Route: api/user/%28:any%29]
in SYSTEMPATH\Router\Router.php on line 739.
 1 SYSTEMPATH\Router\Router.php(207): CodeIgniter\Router\Router->checkDisallowedChars('api/user/(:any)')
 2 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('api/user/(:any)')
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
CRITICAL - 2025-03-07 13:33:06 --> CodeIgniter\HTTP\Exceptions\BadRequestException: The URI you submitted has disallowed characters: "(:any)"
[Method: GET, Route: api/user/%28:any%29]
in SYSTEMPATH\Router\Router.php on line 739.
 1 SYSTEMPATH\Router\Router.php(207): CodeIgniter\Router\Router->checkDisallowedChars('api/user/(:any)')
 2 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('api/user/(:any)')
 3 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\projects\\tcc\\Phpigni\\public\\index.php')
